name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Foundry (optional)
        uses: foundry-rs/foundry-toolchain@v1

      # Install and build only the beralyzer package to avoid monorepo turbo loop
      - name: Install dependencies (beralyzer)
        run: npm --prefix exp/beralyzer ci

      - name: Build (beralyzer)
        run: npm --prefix exp/beralyzer run build

      # Optional: basic format check on tracked files (prettier)
      - name: Prettier check
        run: npx prettier --check "**/*.{ts,tsx,md}" --ignore-path .prettierignore